""" 

=> Error Handling In API Gateway

   -> Every api request can fail at different layers


Client
   │
   ▼
API Gateway
   │
Authentication
Authorization
Validation
Throttling
Integration
   │
   ▼
Backend
   │
Lambda
Database
Other AWS Services

=> Every layer can produce different errors


1. Gateway response

   -> These are the errors generated by API gateway itself , before backend calls

      client -> invalid JWT -> API Gateway -> 401 Unauthorized

      lambda is never invoked


   -> common gateway response

     400 -> bad request

     401 -> Unauthorized 

     403 -> forbidden 

     404 -> resouces not found 

     429 -> too many request 

     500 -> internal api gateway request 

     502 -> bad gateway 

     504 -> gateway timeout

=> Custom gateways Responses

   -> many companies prefer

     {
     
     "error": Authentication failed,
     "message" : invalid jwt token"
     "requestid" : "abc123"

   }

     
=> Lambda errors 

   -> sometime api gateway succeed 

   -> but lambda fails



=> timeout

    -> every backend has a maximum timeout error

       client -> api gateway -> lambda -> db

       db hang

       eventually  504 gateway timeout


=> Retries 

    -> Not for synchronous api gateway integrations


=> fallbacks 
    -> a fallback means

       if the primary service fails , return an alternative response    
"""